export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESTORE_TOKEN = "RESTORE_TOKEN";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ROOM_LOAD_SUCCESS = 'ROOM_LOAD_SUCCESS';
export const ROOM_ADD_SUCCESS = 'ROOM_ADD_SUCCESS';
export const ROOM_EDIT_SUCCESS = 'ROOM_EDIT_SUCCESS';
export const ROOM_DELETE_SUCCESS = 'ROOM_DELETE_SUCCESS';
export const ROOM_LOAD_BY_ID_SUCCESS = 'ROOM_LOAD_BY_ID_SUCCESS';
export const ROOM_LOAD_FAIL = 'ROOM_LOAD_FAIL';